apiVersion: v1
kind: Service
metadata:
  labels:
    app: spacex-test
  name: spacex-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spacex-test
  type: LoadBalancer
status:
  loadBalancer: {}